use coffee_shops;
db.dropDatabase();
db.shops.insertMany(
  [
        {
           "id":"1",
           "name":"Baba Budan",
           "description":"So much more than a coffee shop. We make doughnuts on-site (flavours change daily) & serve food that everyone wants to eat.",
           "logoUrl":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPzwnbc7bJf1ru1ngP31RxZJqwCTzqSGP8GlxdOt52oAK2DITt",
           "location":{
              "street":"Arch 12, 17 East Market Street",
              "postcode":"EH8 8FS",
              "coordinates":[55.9515, -3.1852]
           },
           "estabished":"2016",
           "facilities":{
              "babyChangingUnit":"true",
              "wheelChairAccess":"false"
           },
           "servesLunch":"true",
           "onlineLinks":{
              "instagram":"bababudancoffee",
              "facebook":"bababudancoffee"
           },
           "prices":{
              "priceEspresso":2.2,
              "priceFlatWhite":2.5
           },
           "mainRoaster":"The Barn",
           "method":[
              "espresso",
              "batchBrew"
           ],
           "openingHours":[
              {
                 "day":"1",
                 "opens":"730",
                 "closes":"1600"
              },
              {
                 "day":"2",
                 "opens":"730",
                 "closes":"1600"
              },
              {
                 "day":"3",
                 "opens":"730",
                 "closes":"1600"
              },
              {
                 "day":"4",
                 "opens":"730",
                 "closes":"1600"
              },
              {
                 "day":"5",
                 "opens":"730",
                 "closes":"1700"
              },
              {
                 "day":"6",
                 "opens":"900",
                 "closes":"1700"
              },
              {
                 "day":"7",
                 "opens":"900",
                 "closes":"1700"
              }
           ]
        },
        {
           "id":"2",
           "name":"Lowdown Coffee",
           "description":"A modern cafe offering light food and specialty coffee + tea | hello@lowdowncoffee.com",
           "logoUrl":"https://pbs.twimg.com/profile_images/1036929990393311234/5OIYASdd_400x400.jpg",
           "location":{
              "street":"Ardmore House 40 George Street",
              "postcode":"EH2 2LE",
              "coordinates":[55.9533, -3.1978]
           },
           "estabished":"2016",
           "facilities":{
              "babyChangingUnit":"false",
              "wheelChairAccess":"false"
           },
           "servesLunch":"true",
           "onlineLinks":{
              "instagram":"lowdown_coffee",
              "facebook":"-"
           },
           "prices":{
              "priceEspresso":2.30,
              "priceFlatWhite":2.60
           },
           "mainRoaster":"Koppi",
           "method":[
              "espresso",
              "dripper"
           ],
           "openingHours":[
              {
                 "day":"1",
                 "opens":"800",
                 "closes":"1800"
              },
              {
                 "day":"2",
                 "opens":"800",
                 "closes":"1800"
              },
              {
                 "day":"3",
                 "opens":"800",
                 "closes":"1800"
              },
              {
                 "day":"4",
                 "opens":"800",
                 "closes":"1800"
              },
              {
                 "day":"5",
                 "opens":"800",
                 "closes":"1800"
              },
              {
                 "day":"6",
                 "opens":"900",
                 "closes":"1800"
              },
              {
                 "day":"7",
                 "opens":"1000",
                 "closes":"1800"
              }
           ]
        },
        {
           "id":"3",
           "name":"Cult Espresso",
           "description":"Trying our hand at good coffee. Single origin coffees and an impressive collection of Star Wars Lego.",
           "logoUrl":"https://pbs.twimg.com/profile_images/1020786117405302789/spCaXBAj_400x400.jpg",
           "location":{
              "street":"104 Buccleuch Street",
              "postcode":"EH8 9NG",
              "coordinates":[55.9415, -3.1837]
           },
           "estabished":"2017",
           "facilities":{
              "babyChangingUnit":"false",
              "wheelChairAccess":"false"
           },
           "servesLunch":"true",
           "onlineLinks":{
              "instagram":"cult_espresso",
              "facebook":"CultEspresso"
           },
           "prices":{
              "priceEspresso":2.30,
              "priceFlatWhite":2.60
           },
           "mainRoaster":"Koppi",
           "method":[
              "espresso"
           ],
           "openingHours":[
              {
                 "day":"1",
                 "opens":"800",
                 "closes":"1800"
              },
              {
                 "day":"2",
                 "opens":"800",
                 "closes":"1800"
              },
              {
                 "day":"3",
                 "opens":"800",
                 "closes":"1800"
              },
              {
                 "day":"4",
                 "opens":"800",
                 "closes":"1800"
              },
              {
                 "day":"5",
                 "opens":"800",
                 "closes":"1800"
              },
              {
                 "day":"6",
                 "opens":"900",
                 "closes":"1800"
              },
              {
                 "day":"7",
                 "opens":"900",
                 "closes":"1800"
              }
           ]
        },
        {
           "id":"4",
           "name":"Filament",
           "description":"COFFEE | BAGELS | MUSIC | VIBES",
           "logoUrl":"https://media-cdn.tripadvisor.com/media/photo-s/05/fc/01/10/filament-coffee.jpg",
           "location":{
              "street":"38 Clerk Street",
              "postcode":"EH8 9HX",
              "coordinates":[55.9425, -3.1823]
           },
           "estabished":"2018",
           "facilities":{
              "babyChangingUnit":"false",
              "wheelChairAccess":"false"
           },
           "servesLunch":"false",
           "onlineLinks":{
              "instagram":"filament_coffee",
              "facebook":"filamentcoffee"
           },
           "prices":{
              "priceEspresso":2.30,
              "priceFlatWhite":2.60
           },
           "mainRoaster":"Koppi",
           "method":[
              "espresso"
           ],
           "openingHours":[
              {
                 "day":"1",
                 "opens":"730",
                 "closes":"1800"
              },
              {
                 "day":"2",
                 "opens":"730",
                 "closes":"1800"
              },
              {
                 "day":"3",
                 "opens":"730",
                 "closes":"1800"
              },
              {
                 "day":"4",
                 "opens":"730",
                 "closes":"1800"
              },
              {
                 "day":"5",
                 "opens":"730",
                 "closes":"1800"
              },
              {
                 "day":"6",
                 "opens":"900",
                 "closes":"1800"
              },
              {
                 "day":"7",
                 "opens":"900",
                 "closes":"1700"
              }
           ]
        }
     ]
);
